# Generated by Django 4.1.7 on 2023-03-21 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('DNI', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
                ('Pais', models.CharField(max_length=50)),
                ('Departamento', models.CharField(choices=[('Marketing', 'Marketing'), ('RRHH', 'RRHH'), ('Informática', 'Informática'), ('Administración', 'Administración'), ('Obras', 'Obras'), ('SAT', 'SAT'), ('Presupuestos', 'Presupuestos'), ('Producción', 'Producción'), ('Delineante', 'Delineante'), ('Compras', 'Compras'), ('Comercial', 'Comercial')], max_length=20)),
                ('Email', models.EmailField(default='null@mail.com', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombrePC', models.CharField(max_length=30)),
                ('Dispositivo', models.CharField(choices=[('Telefono', 'Telefono'), ('Ordenador', 'Ordenador')], max_length=9)),
                ('Marca', models.CharField(max_length=30)),
                ('Modelo', models.CharField(max_length=50)),
                ('CPU', models.CharField(max_length=50)),
                ('RAM', models.CharField(choices=[('2GB', '2GB'), ('3GB', '3GB'), ('4GB', '4GB'), ('8GB', '8GB'), ('12GB', '12GB'), ('16GB', '16GB'), ('32GB', '32GB'), ('64GB', '64GB')], max_length=5)),
                ('Almacenamiento', models.CharField(choices=[('16GB', '16GB'), ('32GB', '32GB'), ('64GB', '64GB'), ('128GB', '128GB'), ('256GB', '256GB'), ('512GB', '512GB'), ('1TB', '1TB')], max_length=6)),
                ('NumeroSerie', models.CharField(max_length=50)),
                ('Observaciones', models.CharField(max_length=70)),
                ('FechaInicio', models.DateTimeField(verbose_name='Fecha Inicio')),
                ('FechaDevolucion', models.DateTimeField(verbose_name='Fecha Entrega')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='informes.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Aplicaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programa', models.CharField(max_length=35)),
                ('detalles', models.CharField(max_length=70)),
                ('fecha', models.DateTimeField(verbose_name='Fecha')),
                ('prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='informes.prestamo')),
            ],
        ),
    ]
