# Generated by Django 4.1.7 on 2023-03-22 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informes', '0003_alter_prestamo_fechadevolucion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='Observaciones',
            field=models.CharField(blank=True, max_length=70),
        ),
    ]
