# Generated by Django 4.1.7 on 2023-03-22 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informes', '0006_alter_aplicaciones_detalles_alter_prestamo_cpu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aplicaciones',
            name='fecha',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='aplicaciones',
            name='programa',
            field=models.CharField(blank=True, max_length=35),
        ),
    ]
